
export const posts = [
    {id: 30, title: 'Daniel', 
        description: 'description', 
        category: ['Kittens', 'Programming', 'Artificial intelligence'],
        image:'https://th-thumbnailer.cdn-si-edu.com/faJoWtc8qjIHuCadMQ2MKjt6xmo=/1000x750/filters:no_upscale()/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer/6a/fa/6afa4efa-3f5a-4ea7-90ea-e47173217d59/42-29316901.jpg', 
        author:'author',
        like: 0},
    {id: 31, title: 'Илья Булкин', 
        description: 'description2', 
        category: ['Kittens', 'Programming'],
        image:'https://s7d2.scene7.com/is/image/TWCNews/AP21286725279031_crop?wid=767&hei=431&$wide-bg$', 
        author:'author2',
        like: 0},
    {id: 32, title: 'Valera Glazunov', 
        description: 'description3', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2018/11/Snapseed-1-768x512.jpg', 
        author:'author3',
        like: 0},
    {id: 33, title: 'Сема', 
        description: 'description3', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2018/04/Siberian-tiger-768x512.jpg', 
        author:'author4',
        like: 0},
    {id: 34, title: 'Денис', 
        description: 'description3', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2020/01/leopard-walking-768x512.jpg', 
        author:'author5',
        like: 0},
    {id: 35, title: 'yehor honcharov', 
        description: 'description', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2018/11/Snapseed-1-768x512.jpg', 
        author:'author',
        like: 0},

    {id: 36, title: 'Назар Зозуля', 
        description: 'description2', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2019/05/Snow-leopard-AdobeStock_243151027-570x380.jpg', 
        author:'author2',
        like: 0},
    {id: 37, title: 'Serj Roman', 
        description: 'description3', 
        category: ['Cats', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2019/06/Clouded-leopard-AdobeStock_177858806-768x512.jpg', 
        author:'author3',
        like: 14},
    {id: 38, title: 'Даня', 
        description: 'description3',
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2020/05/Asiatic-golden-cat-Flikr-creative-commons-768x512.jpg', 
        author:'author4',
        like: 0},
    {id: 39, title: 'Богдан Рубанов', 
        description: 'description3', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2020/01/serval-768x513.jpg', 
        author:'author5',
        like: 0},
    {id: 40, title: 'Панасенко Діана', 
        description: 'description', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2018/04/Caracal-570x380.jpg', 
        author:'author',
        like: 0},

    {id: 41, title: 'Rinat Kachenko', 
        description: 'description2', 
        category: ['Kittens', 'Programming', 'Chat-Bot'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2018/05/DSC_0731-570x380.jpg', 
        author:'author2',
        like: 0},
    {id: 42, title: 'Антон Примуш', 
        description: 'description3', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2019/04/oncilla-AdobeStock_128887437-570x380.jpg', 
        author:'author3',
        like: 0},
    {id: 43, title: 'Dima Pysmennyi', 
        description: 'description3', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2018/04/Bobcat-in-the-snow-570x380.jpg', 
        author:'author4',
        like: 0},
    {id: 44, title: 'Миша', 
        description: 'description3', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2020/05/Eurasian-lynx-AdobeStock_246336076-768x512.jpg', 
        author:'author5',
        like: 0},
    {id: 45, title: 'Kemilli', 
        description: 'description', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2020/05/Bobcat-AdobeStock_177846262-768x512.jpg', 
        author:'author',
        like: 0},

    {id: 46, title: 'Vanya Kratenko', 
        description: 'description2', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2020/01/two-cheetahs-768x512.jpg', 
        author:'author2',
        like: 0},
    {id: 47, title: 'Илья Булкин', 
        description: 'description2', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2020/05/Black-footed-cat-AdobeStock_121247249-768x513.jpg', 
        author:'author2',
        like: 0},
    {id: 48, title: 'Nazar Zozulya', 
        description: 'description3', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2018/04/Sand-cat-570x380.jpg', 
        author:'author3',
        like: 0},
    {id: 49, title: 'Фатуев Михайло', 
        description: 'description3', 
        category: ['Kittens', 'Programming'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2018/03/African-wild-cat-570x380.jpg', 
        author:'author4',
        like: 0},
    {id: 50, title: 'Дanilo Koshnaryov', 
        description: 'description3', 
        category: ['Kittens', 'Programming', 'Artificial intelligence'],
        image:'https://www.thewildlifediaries.com/wp-content/uploads/2020/05/European-wild-cat-AdobeStock_164919121-768x512.jpg', 
        author:'author5',
        like: 0},
]